version: '3.8'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: "bdModule"
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: 'admin'
        MONGO_INITDB_ROOT_PASSWORD: '1234'
        MONGO_INITDB_DATABASE: 'test'
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
    networks:
      net:
        ipv4_address: 172.18.0.117
networks:
  net:
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
